//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IM_Projection.h
//  @ Date : 20/04/2007
//  @ Author :
//
//


#if !defined(_IM_PROJECTION_H)
#define _IM_PROJECTION_H

#include "transform.h"
#include "image.hh"
namespace fogrimmi
{
  //==========================================================
  /// Specialisation Transformation - Projection
  //==========================================================
  class IM_Projection : public IM_Transform
  {
  public:
    //----------------------------------------------------------
    /// Constructeur par défaut
    //----------------------------------------------------------
    IM_Projection(){};


    //----------------------------------------------------------
    /// calcul de la projection
    //----------------------------------------------------------
    static IM_Box projection(IM_Box boxImgSrc, IM_Box boxSrc, IM_Box boxImgDest);

    //----------------------------------------------------------
    /// calcul du ratio entre deux cadres
    //----------------------------------------------------------
    static float getRatio(IM_Box boxImgSrc, IM_Box boxImgDest);
  };
}//namespace fogrimmi
#endif  //_IM_PROJECTION_H
