//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Image Management
//  @ File Name : IM_Transform.h
//  @ Date : 20/04/2007
//  @ Author : Thibaut Aubrun : http://aubrun.thibaut.free.fr
//
//


#ifndef _IM_TRANSFORM_H
#define _IM_TRANSFORM_H

#include "image.hh"

namespace fogrimmi
{
  //==========================================================
  /// Classe abstraite gerant les Transformations
  //==========================================================
  class IM_Transform
  {
    public:
    IM_Transform(){
      aborted = false;
    }
    //----------------------------------------------------------
    /// Destructeur
    //----------------------------------------------------------
    virtual ~IM_Transform(){
      #ifdef _DEBUG_
        std::cout<<"Transform destruction\n";
      #endif
      };

    virtual void abort(bool _aborted)
    {
      aborted = _aborted;
    };

    protected:
      bool aborted;


  };
}//namespace fogrimmi
#endif  //_IM_TRANSFORM_H
