//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IM_Strip.h
//  @ Date : 20/04/2007
//  @ Author :
//
//


#if !defined(_IM_STRIP_H)
#define _IM_STRIP_H

#include "component.h"
namespace fogrimmi
{

  //==========================================================
  /// Gestionnaire de ligne - charge en memoire
  //==========================================================
  class IM_Strip: public IM_Component
  {
  public:


    //----------------------------------------------------------
    /// Constructeur
    //----------------------------------------------------------
    IM_Strip(TIFF& tif,unsigned short int _col, unsigned short int _row);

    //----------------------------------------------------------
    /// Constructeur
    //----------------------------------------------------------
    IM_Strip(unsigned short int _col, unsigned short int _row);

    //----------------------------------------------------------
    /// Destructeur
    //----------------------------------------------------------
    ~IM_Strip();

    //----------------------------------------------------------
    /// Read a strip (cols x rows) and save it in memory
    //----------------------------------------------------------
    bool read(TIFF& tif, unsigned short int cols, unsigned short int rows, unsigned short int colorMode=3);

    //----------------------------------------------------------
    /// Write a strip (cols x rows) in a tif
    //----------------------------------------------------------
    bool write(TIFF &tif, unsigned short int sizeH, unsigned int sizeW=0);

    //----------------------------------------------------------
    /// Retrieve a pixel value at specified location
    //----------------------------------------------------------
    void getPixelValue(IM_Pixel &pix,unsigned short int cols, unsigned short int rows, unsigned short int colorMode=3);

    //----------------------------------------------------------
    /// Modifie la valeur d'un pixel
    //----------------------------------------------------------
    void setPixelValue(const IM_Pixel &pix, unsigned short int sizeH, unsigned int sizeW = 0, unsigned short int colorMode=3);

    //----------------------------------------------------------
    /// Modifie en une tuile entiere
    //----------------------------------------------------------
    void addData(uint8* _data){ buffer = _data;};

  private:

  };
}//namespace fogrimmi
#endif  //_IM_STRIP_H
