//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IM_Rotation.h
//  @ Date : 20/04/2007
//  @ Author :
//
//


#if !defined(_IM_ROTATION_H)
#define _IM_ROTATION_H

#include "image.hh"
#include "transform.h"

namespace fogrimmi
{
  //==========================================================
  /// Specialisation Transformation - Rotation
  //==========================================================
  class IM_Rotation : public IM_Transform
  {
  public:
    //----------------------------------------------------------
    /// calcul de la rotation
    //----------------------------------------------------------
    bool rotation(IM_Image* img, float angle);
  };
}//namespace Im
#endif  //_IM_ROTATION_H
