//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Image Management
//  @ File Name : IM_Tile.h
//  @ Date : 20/04/2007
//  @ Author : Thibaut Aubrun : http://aubrun.thibaut.free.fr
//
//


#if !defined(_IM_TILE_H)
#define _IM_TILE_H

#include "component.h"
namespace fogrimmi
{

  //==========================================================
  /// Gestionnaire de tuile - charge en memoire
  //==========================================================
  class IM_Tile: public IM_Component
  {
  public:

    //----------------------------------------------------------
    /// Constructeur
    //----------------------------------------------------------
    IM_Tile(TIFF& tif,unsigned short int _col, unsigned short int _row);

    //----------------------------------------------------------
    /// Constructeur
    //----------------------------------------------------------
    IM_Tile(unsigned short int _col, unsigned short int _row);

    //----------------------------------------------------------
    /// Destructeur
    //----------------------------------------------------------
    ~IM_Tile();

    //----------------------------------------------------------
    /// Read a tile (cols x rows) and save it in memory
    //----------------------------------------------------------
    bool read( TIFF& tif, unsigned short int cols, unsigned  short int rows, unsigned  short int colorMode=3);

    //----------------------------------------------------------
    /// Write a tile (cols x rows) and save it in memory
    //----------------------------------------------------------
    bool write(TIFF &tif, unsigned short int sizeH, unsigned int sizeW);

    //----------------------------------------------------------
    /// Retrieve a pixel value at specified location
    //----------------------------------------------------------
    void getPixelValue(IM_Pixel &pix,unsigned short int cols, unsigned short int rows, unsigned short int colorMode=3);

    //----------------------------------------------------------
    /// Modifie la valeur d'un pixel
    //----------------------------------------------------------
    void setPixelValue(const IM_Pixel &pix, unsigned short int sizeH, unsigned int sizeW = 0, unsigned short int colorMode=3);


    //----------------------------------------------------------
    /// Modifie en une tuile entiere
    //----------------------------------------------------------
    void addData(uint8* _data);

  private:

  };
}//namespace fogrimmi
#endif  //_IM_TILE_H
